version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://authenticator:password@postgres:5432/app_db
      PGRST_DB_SCHEMA: public,private
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_LOG_QUERY: "main-query"
      PGRST_LOG_LEVEL: "debug"
      # PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: "gRhaJ99BB3EhcjpwI1WTA7pLywa+J25X"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
